### ISSUE TITLE
Add pets element in no page found 

### ISSUE THREAD

**Issue by jvera701** [Cortesjohnj/top-app#15]
The add pets element can be found in the 404 error page. Attached is an screenshot of this

<img width="960" alt="bug" src="https://user-images.githubusercontent.com/12566954/132971118-3609d0bd-710c-481e-bee6-be026635ee63.PNG">

**Comment by juanan150** [comment]
This is not a 404 page, but a valid page with an invalid `foundationId`, that's why it is showing the message to the user. What I did is that I changed the message when the user is a foundation:
![imagen](https://user-images.githubusercontent.com/58634102/133517826-3328a815-a876-4dc6-ae59-7f61fb363c5b.png)

It is now under approval. I'll close this issue as soon as it is merged in `develop`

**Comment by juanan150** [comment]
Issue solved.
